services:
  slskd:
    image: ghcr.io/slskd/slskd:latest
    container_name: slskd-server
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./slskd.yml:/app/slskd.yml:ro
      - ./downloads:/downloads
      - ./slskd-data:/app/data
    ports:
      - "5030:5030"
      - "50300:50300"
    networks:
      - slsk-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: soulseek-bulk-downloader
    depends_on:
      - slskd
    command: sh -c "sleep 15 && python main.py"
    env_file:
      - .env
    volumes:
      - ./songs.txt:/app/songs.txt
    networks:
      - slsk-net

networks:
  slsk-net:
    driver: bridge

